name: Build

on:
  push:
    branches: develop

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
        with:
          lfs: true
          ref: develop

      - uses: actions/cache@v1.1.0
        with:
          path: /Library
          key: ${{ runner.os }}
          restore-keys: ${{ runner.os }}

      - uses: webbertakken/unity-builder@v1.0
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: ${{ github.workspace }}
          unityVersion: 2019.3.13f1
          targetPlatform: StandaloneWindows64
          buildName: Boing Build:${{ github.run.number }} Commit:${ GITHUB_SHA::7 }


      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build

      - uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r build.zip build/StandaloneWindows64


      - run: mv build.zip "Boing Build:${{ github.run.number }} Commit:${ GITHUB_SHA::7 }"

      - name: Upload to Google Drive
        uses: satackey/action-google-drive@v1
        with:
          skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE_JSON }}
          upload-from: "Boing Build:${{ github.run.number }} Commit:${ GITHUB_SHA::7 }"
          upload-to: Boing/Builds
          google-client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
          google-client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}