name: Merge

on:
  push:
    branches: 
      - master
      - william

jobs:

  build:

    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v2
        
    - name: Run a multi-line script
      run: |
        git fetch 
        git checkout william
        git checkout develop
        git branch
        git merge william
        git status

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
