name: Merge

on:
  push:
    branches: 
      - master
      - william

jobs:

  build:

    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v2
      with: 
        ref: 'william'

    - uses: actions/checkout@v2
      with: 
        ref: 'devlop'

    - name: Run a multi-line script
      run: |
        git branch
        git merge william
        git push
