name: Merge

on:
  push:
    branches: 
      - master
      - william

jobs:

  build:

    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v2
      with: 
        ref: 'william'
        clean: 'false'

    - uses: actions/checkout@v2
      with: 
        ref: 'devlop'
        clean: 'false'
        
    - name: Run a multi-line script
      run: |
        git checkout origin/devlop
        git branch
        git merge william
        git push
