name: Merge

on:
  push:
    branches: 
      - william

jobs:

  build:

    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v2
      with:
        ref: master

    - name: Install UnityYAMLMerge
      run: |
        git config --local merge.tool unityyamlmerge
        git config --local mergetool.unityyamlmerge.trustExitCode true
        git config --local mergetool.unityyamlmerge.cmd "'${{ github.workspace }}\.github\workflows\UnityYAMLMerge.exe'  merge -p -o ${{ github.workspace }}\mergeConflicts.txt `"`$BASE`" `"`$REMOTE`" `"`$LOCAL`" `"`$MERGED"

    - uses: oleksiyrudenko/gha-git-credentials@v1
      with:
        token: '${{ secrets.GITHUB_TOKEN }}'
        
    - name: Fetch and Checkout
      run: |
        git fetch 
        git checkout ${GITHUB_REF##*/}
        git checkout develop
      shell: bash

    - name: Normal Merge
      run: git merge ${{ github.ref }}

    - name: YAML Merge
      run: |
        git mergetool --tool=unityyamlmerge --no-prompt
        git commit -m "Automatic Merge with UnityYAMLMerge"
        git status

    - name: Upload Artifacts
      if: ${{ failure() }}
      uses: actions/upload-artifact@v1
      with:
          name: mergeConflicts
          path: mergeConflicts.txt

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'develop'