name: Merge

on:
  push:
    branches: 
      - william

jobs:

  build:

    runs-on: self-hosted

    steps:

    - uses: actions/checkout@v2
      with:
        ref: master

    - name: Install UnityYAMLMerge
      run: |
        git config --local merge.tool unityyamlmerge
        git config --local mergetool.unityyamlmerge.trustExitCode false
        git config --local mergetool.unityyamlmerge.cmd ""'<D:/a/git-unity-test-2/git-unity-test-2/.github/workflows/UnityYAMLMerge.exe>'  merge -p "$BASE" "$REMOTE" "$LOCAL" "$MERGED"""
        git config --list --show-origin
        
    - name: Run a multi-line script
      run: |
        git fetch 
        git checkout ${GITHUB_REF##*/}
        echo ${GITHUB_REF##*/}
        git checkout develop
        git branch
        git merge ${GITHUB_REF##*/}
        git status
      shell: bash

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'develop'
